
import type { WordForm, WordFormType, Question } from '../types';

export const WORDS_PER_PAGE = 10;

const wordListData: WordForm[] = [
    // A
    { verb: 'enable', noun_thing: 'ability', adjective: 'able', adverb: 'ably' },
    { noun_thing: 'abruptness', adjective: 'abrupt', adverb: 'abruptly' },
    { noun_thing: 'absence', noun_person: 'absentee', adjective: 'absent', adverb: 'absently' },
    { noun_thing: ['academy', 'academia'], noun_person: 'academician', adjective: 'academic' },
    { verb: 'access', noun_thing: ['accession', 'accessibility'], adjective: 'accessible' },
    { verb: 'accommodate', noun_thing: 'accommodation', adjective: ['accommodating', 'accommodative'] },
    { verb: 'accord', noun_thing: 'accordance', adjective: 'accordant', adverb: 'accordingly' },
    { verb: 'accustom', adjective: 'accustomed' },
    { verb: 'achieve', noun_thing: 'achievement', noun_person: 'achiever', adjective: 'achievable' },
    { verb: 'acquaint', noun_thing: 'acquaintance' },
    { verb: 'act', noun_thing: ['action', 'activity'], noun_person: ['actor', 'actress'], adjective: 'active', adverb: 'actively' },
    { noun_person: 'activist', noun_thing: 'activity', adjective: 'active' },
    { verb: 'addict', noun_thing: 'addiction', noun_person: 'addict', adjective: 'addicted' },
    { verb: 'admire', noun_thing: 'admiration', noun_person: 'admirer', adjective: 'admirable' },
    { noun_thing: ['advantage', 'disadvantage'], adjective: 'advantageous', adverb: 'advantageously' },
    { verb: 'adventure', noun_person: 'adventurer', adjective: 'adventurous' },
    { verb: 'advertise', noun_thing: ['advertisement', 'advertising'], noun_person: 'advertiser' },
    { verb: 'advise', noun_thing: 'advice', noun_person: 'adviser', adjective: 'advisable', adverb: 'advisedly' },
    { verb: 'affect', noun_thing: 'affection', adjective: ['affecting', 'affective', 'affectionate', 'affected'], adverb: 'affectively' },
    { verb: 'aggress', noun_thing: 'aggression', noun_person: 'aggressor', adjective: 'aggressive', adverb: 'aggressively' },
    { verb: 'agree', noun_thing: 'agreement', adjective: 'agreeable', adverb: 'agreeably' },
    { noun_thing: 'agriculture', noun_person: 'agriculturalist', adjective: 'agricultural' },
    { verb: 'alarm', noun_thing: 'alarm', noun_person: 'alarmist', adjective: ['alarming', 'alarmed'], adverb: 'alarmingly' },
    { verb: 'alert', noun_thing: 'alertness', adjective: 'alert', adverb: 'alertly' },
    { verb: 'alter', noun_thing: 'alteration', adjective: 'alterable' },
    { verb: 'alternate', noun_thing: ['alternative', 'alternation'], adjective: 'alternative', adverb: ['alternatively', 'alternately'] },
    { verb: 'amaze', noun_thing: 'amazement', adjective: ['amazing', 'amazed'], adverb: 'amazingly' },
    { noun_thing: 'ambition', adjective: 'ambitious', adverb: 'ambitiously' },
    { noun_thing: 'america', noun_person: 'american', adjective: 'american' },
    { verb: 'amuse', noun_thing: 'amusement', adjective: ['amusing', 'amused'], adverb: 'amusingly' },
    { noun_thing: 'ancientness', adjective: 'ancient', adverb: 'anciently' },
    { noun_thing: 'anger', adjective: 'angry', adverb: 'angrily' },
    { verb: 'announce', noun_thing: 'announcement', noun_person: 'announcer' },
    { verb: 'annoy', noun_thing: 'annoyance', adjective: ['annoying', 'annoyed'] },
    { verb: 'apologize', noun_thing: 'apology', noun_person: 'apologist' },
    { verb: 'applaud', noun_thing: 'applause', noun_person: 'applauder' },
    { verb: 'apply', noun_thing: ['application', 'appliance'], noun_person: 'applicant', adjective: 'applicable', adverb: 'applicably' },
    { verb: 'appoint', noun_thing: 'appointment', adjective: 'appointed' },
    { verb: 'approximate', noun_thing: 'approximation', adjective: 'approximate', adverb: 'approximately' },
    { verb: 'argue', noun_thing: 'argument', adjective: 'argumentative' },
    { verb: 'arrange', noun_thing: 'arrangement' },
    { verb: 'arrive', noun_thing: 'arrival' },
    { noun_thing: 'art', noun_person: 'artist', adjective: ['artistic', 'artless'], adverb: ['artistically', 'artlessly'] },
    { verb: 'assign', noun_thing: 'assignment', noun_person: 'assigner' },
    { verb: 'assist', noun_thing: ['assistance', 'assistantship'], noun_person: 'assistant' },
    { verb: 'associate', noun_thing: ['association', 'sociability'], adjective: 'associative' },
    { verb: 'attend', noun_thing: ['attendance', 'attention', 'attentiveness'], noun_person: 'attendant', adjective: 'attentive', adverb: 'attentively' },
    { verb: 'attract', noun_thing: 'attraction', adjective: 'attractive', adverb: 'attractively' },
    { noun_thing: 'australia', noun_person: 'australian', adjective: 'australian' },
    { noun_thing: 'austria', noun_person: 'austrian', adjective: 'austrian' },
    { verb: 'authorize', noun_thing: ['authority', 'authorization'], noun_person: ['author', 'authoress'], adjective: 'authoritative', adverb: 'authoritatively' },
    { verb: 'automate', noun_thing: 'automation', adjective: 'automatic', adverb: 'automatically' },
    { noun_thing: 'availability', adjective: 'available' },
    { verb: 'avoid', noun_thing: 'avoidance', adjective: 'avoidable' },
    { noun_thing: 'awareness', adjective: 'aware' },
    { noun_thing: 'awfulness', adjective: 'awful', adverb: 'awfully' },
    // B
    { noun_thing: 'badness', adjective: 'bad', adverb: 'badly' },
    { noun_thing: 'bagginess', adjective: 'baggy' },
    { noun_thing: ['baldness', 'balding'], adjective: 'bald', adverb: 'baldly' },
    { verb: 'beautify', noun_thing: 'beauty', noun_person: 'beautician', adjective: 'beautiful', adverb: 'beautifully' },
    { verb: 'behave', noun_thing: ['behavior', 'behaviour'], adjective: 'behavioral' },
    { verb: 'benefit', noun_thing: 'benefit', adjective: 'beneficial' },
    { verb: 'begin', noun_thing: 'beginning', noun_person: 'beginner' },
    { noun_thing: 'bigness', adjective: 'big', adverb: 'bigly' },
    { noun_thing: 'biology', noun_person: 'biologist', adjective: 'biological', adverb: 'biologically' },
    { noun_thing: 'birth', adjective: 'born' }, // birthday is a compound noun, born is more like an adjective/participle
    { verb: 'blind', noun_thing: 'blindness', adjective: 'blind', adverb: 'blindly' },
    { verb: 'board', noun_thing: ['board', 'boarding', 'boardwages'], noun_person: 'boarder' },
    { verb: 'bore', noun_thing: 'boredom', adjective: ['boring', 'bored'] },
    { noun_thing: 'botany', noun_person: 'botanist', adjective: 'botanical' },
    { noun_thing: ['braveness', 'bravery'], adjective: 'brave', adverb: 'bravely' },
    { noun_thing: ['brightness', 'brilliance'], adjective: ['bright', 'brilliant'], adverb: ['brightly', 'brilliantly'] },
    { noun_thing: 'brotherhood', noun_person: 'brother', adjective: 'brotherly' },
    { noun_thing: 'buddhism', noun_person: 'buddhist', adjective: 'buddhist' },
    { verb: 'build', noun_thing: 'building', noun_person: 'builder' },
    { verb: 'burn', noun_thing: 'burn', noun_person: 'burner', adjective: 'burning' },
    { noun_thing: 'bush', adjective: 'bushy' },
    { noun_thing: 'business', noun_person: 'businessman', adjective: 'businesslike' },
    { verb: 'busy', adjective: 'busy', adverb: 'busily' },
    { verb: 'button', noun_thing: 'button' },
    // C
    { verb: 'calculate', noun_thing: 'calculation', noun_person: 'calculator', adjective: 'calculative' },
    { verb: 'can', noun_thing: 'can', adjective: 'canned' },
    { noun_thing: 'canada', noun_person: 'canadian', adjective: 'canadian' },
    { verb: 'care', noun_thing: ['care', 'carefulness', 'carelessness'], adjective: ['careful', 'careless'], adverb: ['carefully', 'carelessly'] },
    { verb: 'carry', noun_thing: 'carriage' },
    { noun_thing: ['casualty', 'casualness'], adjective: 'casual', adverb: 'casually' },
    { verb: 'celebrate', noun_thing: 'celebration', noun_person: 'celebrant' },
    { verb: 'centralize', noun_thing: 'center', adjective: 'central', adverb: 'centrally' },
    { noun_thing: 'certainty', adjective: 'certain', adverb: 'certainly' },
    { verb: 'challenge', noun_thing: 'challenge', noun_person: 'challenger', adjective: 'challenging' },
    { noun_thing: ['champion', 'championship'], noun_person: 'champion' },
    { verb: 'change', noun_thing: 'change', adjective: ['changeable', 'changeless'] },
    { noun_thing: ['charity', 'charitableness'], adjective: 'charitable' },
    { verb: 'cheapen', noun_thing: 'cheapness', adjective: 'cheap', adverb: 'cheaply' },
    { verb: 'cheer', noun_thing: 'cheerfulness', adjective: 'cheerful', adverb: 'cheerfully' },
    { noun_thing: 'chemistry', noun_person: 'chemist', adjective: 'chemical', adverb: 'chemically' },
    { noun_thing: 'chief', adjective: 'chief', adverb: 'chiefly' },
    { noun_thing: ['childhood', 'childishness'], noun_person: ['child', 'children'], adjective: 'childish' },
    { noun_thing: 'china', noun_person: 'chinese', adjective: 'chinese' },
    { verb: 'choose', noun_thing: 'choice', adjective: 'choosy' },
    { noun_thing: ['citizen', 'citizenship'], noun_person: 'citizen' },
    { verb: 'claim', noun_thing: 'claim', noun_person: 'claimant' },
    { verb: 'classify', noun_thing: 'class', noun_person: 'classmate', adjective: 'classy' },
    { noun_thing: 'classic', adjective: 'classic' },
    { verb: 'clean', noun_thing: 'cleanliness', noun_person: 'cleaner', adjective: ['clean', 'cleanable'], adverb: 'cleanly' },
    { noun_thing: 'clearness', adjective: 'clear', adverb: 'clearly' },
    { noun_thing: 'cleverness', adjective: 'clever', adverb: 'cleverly' },
    { verb: 'climb', noun_person: 'climber', adjective: 'climbable' },
    { verb: 'close', noun_thing: 'closeness', adjective: 'close', adverb: 'closely' },
    { verb: 'clothe', noun_thing: ['cloth', 'clothes', 'clothing'] },
    { noun_thing: 'cloud', adjective: ['cloudy', 'cloudless'] },
    { verb: 'coast', noun_thing: ['coast', 'coaster', 'coastline'], adjective: 'coastal', adverb: 'coastward' },
    { verb: 'coat', noun_thing: 'coating', adjective: 'coated' },
    { verb: 'co-educate', noun_thing: 'co-education', adjective: 'co-educational' },
    { noun_thing: 'coldness', adjective: 'cold', adverb: 'coldly' },
    { verb: 'collapse', adjective: 'collapsible' },
    { verb: 'collect', noun_thing: ['collection', 'collective'], noun_person: 'collector', adjective: 'collective' },
    { verb: 'color', noun_thing: ['color', 'colorant'], noun_person: 'colorist', adjective: ['colored', 'colorful', 'colorless'] },
    { verb: 'combine', noun_thing: 'combination' },
    { noun_thing: 'comfort', adjective: ['comfortable', 'uncomfortable', 'comfortless'], adverb: ['comfortably', 'uncomfortably'] },
    { verb: 'command', noun_thing: 'command', noun_person: 'commander' },
    { verb: 'commune', noun_thing: ['community', 'communication'], noun_person: 'communicant', adjective: 'communicative' },
    { verb: 'compare', noun_thing: 'comparison', adjective: 'comparative' },
    { verb: 'compete', noun_thing: 'competition', noun_person: 'competitor', adjective: 'competitive' },
    { verb: 'complain', noun_thing: 'complaint' },
    { verb: 'complete', noun_thing: 'completion', adjective: 'complete', adverb: 'completely' },
    { verb: 'compel', noun_thing: 'compulsion', adjective: 'compulsory' },
    { verb: 'compose', noun_thing: 'composition', noun_person: 'composer' },
    { verb: 'compute', noun_thing: 'computation', noun_person: 'computer' },
    { verb: 'conclude', noun_thing: 'conclusion', adjective: 'conclusive' },
    { noun_thing: 'condition', adjective: 'conditional' },
    { verb: 'confide', noun_thing: 'confidence', adjective: 'confident' },
    { verb: 'confuse', noun_thing: 'confusion', adjective: 'confused' },
    { verb: 'connect', noun_thing: 'connection' },
    { verb: 'conquer', noun_person: 'conqueror' },
    { verb: 'consider', noun_thing: 'consideration', adjective: 'considerable' },
    { verb: 'construct', noun_thing: 'construction', adjective: 'constructive' },
    { verb: 'consume', noun_thing: 'consumption', noun_person: 'consumer' },
    { verb: 'contain', noun_person: 'container' },
    { verb: 'continue', noun_thing: 'continuation', adjective: 'continuous' },
    { verb: 'contribute', noun_thing: 'contribution', noun_person: 'contributor' },
    { verb: 'convenience', adjective: 'convenient' },
    { verb: 'cook', noun_thing: 'cookery', noun_person: 'cook' },
    { verb: 'cool', noun_thing: 'coolness' },
    { verb: 'cooperate', noun_thing: 'cooperation', adjective: 'cooperative' },
    { verb: 'correct', noun_thing: 'correction', adjective: 'correct' },
    { verb: 'correspond', noun_thing: 'correspondence', noun_person: 'correspondent' },
    { noun_thing: 'courage', adjective: 'courageous' },
    { verb: 'cover', noun_thing: 'coverage' },
    { verb: 'create', noun_thing: 'creation', noun_person: 'creator', adjective: 'creative' },
    { noun_thing: 'crime', noun_person: 'criminal' },
    { verb: 'criticize', noun_thing: 'criticism', noun_person: 'critic' },
    { verb: 'crowd', adjective: 'crowded' },
    { verb: 'cruelty', adjective: 'cruel' },
    { noun_thing: 'culture', adjective: 'cultural' },
    { verb: 'cure', adjective: 'curable' },
    { noun_thing: 'curiosity', adjective: 'curious' },
    { verb: 'damage', noun_thing: 'damage' },
    { verb: 'danger', adjective: 'dangerous' },
    { verb: 'darken', noun_thing: 'darkness' },
    { noun_thing: 'day', adjective: 'daily' },
    { verb: 'deafen', adjective: 'deaf' },
    { verb: 'decide', noun_thing: 'decision', adjective: 'decisive' },
    { verb: 'decorate', noun_thing: 'decoration', noun_person: 'decorator' },
    { noun_thing: 'deepness', adjective: 'deep' },
    { verb: 'defend', noun_thing: 'defense', noun_person: 'defendant' },
    { verb: 'deliver', noun_thing: 'delivery' },
    { verb: 'depart', noun_thing: 'departure' },
    { verb: 'depend', noun_thing: 'dependence', adjective: 'dependent' },
    { verb: 'describe', noun_thing: 'description' },
    { verb: 'destroy', noun_thing: 'destruction', adjective: 'destructive' },
    { verb: 'determine', noun_thing: 'determination' },
    { verb: 'develop', noun_thing: 'development' },
    { verb: 'die', noun_thing: 'death', adjective: 'dead' },
    { verb: 'differ', noun_thing: 'difference', adjective: 'different' },
    { noun_thing: 'difficulty', adjective: 'difficult' },
    { verb: 'direct', noun_thing: 'direction', noun_person: 'director' },
    { verb: 'disappear', noun_thing: 'disappearance' },
    { verb: 'discover', noun_thing: 'discovery' },
    { verb: 'discuss', noun_thing: 'discussion' },
    { verb: 'disturb', noun_thing: 'disturbance' },
    { verb: 'divide', noun_thing: 'division' },
    { verb: 'divorce', adjective: 'divorced' },
    { verb: 'do', noun_thing: 'deed' },
    { verb: 'doubt', adjective: 'doubtful' },
    { verb: 'draw', noun_thing: 'drawing' },
    { verb: 'drink', noun_thing: 'drink' },
    { verb: 'drive', noun_person: 'driver' },
    { verb: 'drop', noun_thing: 'drop' },
    { noun_thing: 'drunkenness', adjective: 'drunk' },
    { verb: 'dry', noun_thing: 'dryness' },
    { noun_thing: 'dust', adjective: 'dusty' },
    { noun_thing: 'dye', verb: 'dye' },
    { verb: 'earn', noun_thing: 'earnings' },
    { noun_thing: 'ease', adjective: 'easy' },
    { verb: 'eat', noun_thing: 'eating', adjective: 'edible' },
    { verb: 'economize', noun_thing: 'economy', noun_person: 'economist', adjective: 'economic' },
    { verb: 'educate', noun_thing: 'education', adjective: 'educational' },
    { verb: 'elect', noun_thing: 'election' },
    { verb: 'employ', noun_thing: 'employment', noun_person: ['employer', 'employee'] },
    { verb: 'encourage', noun_thing: 'encouragement' },
    { verb: 'end', noun_thing: 'end', adjective: 'endless' },
    { verb: 'endanger', noun_thing: 'danger', adjective: 'dangerous' },
    { verb: 'enjoy', noun_thing: 'enjoyment', adjective: 'enjoyable' },
    { verb: 'enter', noun_thing: 'entrance' },
    { verb: 'entertain', noun_thing: 'entertainment' },
    { verb: 'envy', noun_thing: 'envy', adjective: 'envious' },
    { verb: 'equal', noun_thing: 'equality' },
    { verb: 'examine', noun_thing: 'examination', noun_person: 'examinee' },
    { verb: 'excel', noun_thing: 'excellence', adjective: 'excellent' },
    { verb: 'excite', noun_thing: 'excitement', adjective: 'exciting' },
    { verb: 'excuse', noun_thing: 'excuse' },
    { verb: 'exhibit', noun_thing: 'exhibition' },
    { verb: 'exist', noun_thing: 'existence' },
    { verb: 'expect', noun_thing: 'expectation' },
    { verb: 'expense', adjective: 'expensive' },
    { verb: 'explain', noun_thing: 'explanation' },
    { verb: 'explode', noun_thing: 'explosion' },
    { verb: 'explore', noun_thing: 'exploration', noun_person: 'explorer' },
    { verb: 'extend', noun_thing: 'extension' }
];

export const TOTAL_PAGES = Math.ceil(wordListData.length / WORDS_PER_PAGE);

export function getWordsForPage(page: number): WordForm[] {
    const startIndex = (page - 1) * WORDS_PER_PAGE;
    const endIndex = startIndex + WORDS_PER_PAGE;
    return wordListData.slice(startIndex, endIndex);
}

const formDisplayNames: Record<WordFormType, string> = {
    verb: "verb",
    noun_thing: "noun (thing)",
    noun_person: "noun (person)",
    adjective: "adjective",
    adverb: "adverb",
};

export const getFormDisplayName = (form: WordFormType) => formDisplayNames[form];

export function generateQuestionsForWords(words: WordForm[]): Question[] {
    return words.map(word => {
        const availableForms = (Object.keys(word) as WordFormType[]).filter(key => word[key]);

        if (availableForms.length < 2) {
            // Fallback for incomplete data
            return {
                baseWord: 'error',
                baseForm: 'verb',
                targetForm: 'noun_thing',
                answer: 'data missing',
            };
        }

        let baseFormIndex = Math.floor(Math.random() * availableForms.length);
        let targetFormIndex = Math.floor(Math.random() * availableForms.length);

        while (baseFormIndex === targetFormIndex) {
            targetFormIndex = Math.floor(Math.random() * availableForms.length);
        }

        const baseForm = availableForms[baseFormIndex];
        const targetForm = availableForms[targetFormIndex];

        const baseWords = word[baseForm]!;
        const baseWord = Array.isArray(baseWords) ? baseWords[Math.floor(Math.random() * baseWords.length)] : baseWords;
        
        const answer = word[targetForm]!;

        return { baseWord, baseForm, targetForm, answer };
    });
}
